import Head from "next/head";
import Home from "@/components/Home";
import Navbar from "@/components/Navbar";
import HeroApi from "@/components/Home/HeroApi";
import Quran from "@/components/Home/Quran";

export default function Data({ items }) {
  return (
    <>
      <Head>
        <title>هذا هو الإسلام</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroApi items={items} />
      <Quran />
    </>
  );
}

export async function getStaticProps() {
  const itemsRes = await fetch(
    `https://app.thisislam.net/api/get_home/${"ar"}`
  );
  const items = await itemsRes.json();

  return {
    props: {
      items,
    },
    revalidate: 10,
  };
}
