import Head from "next/head";
import Home from "@/components/Home";
import Navbar from "@/components/Navbar";

export default function App() {
  return (
    <>
      <Head>
        <title>هذا هو الإسلام</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Home />
    </>
  );
}
