import Head from "next/head";
import Image from "next/image";
import { Cairo } from "next/font/google";
import Home from "@/components/Home";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Home/Hero";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900", "1000"],
  style: ["normal"],
});
export default function App() {
  return (
    <>
      <Head>
        <title>هذا هو الإسلام</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={` ${cairo.className}`}>
        <Home />
      </main>
    </>
  );
}
